stages:
  data_ingestion:
    cmd: python src/data_ingestion.py
    deps:
      - src/data_ingestion.py
    outs:
      - data/raw/dataset.csv
  preprocess:
    cmd: python src/preprocessing.py
    deps:
      - src/preprocessing.py
      - data/raw/dataset.csv
    outs:
      - data/processed
  train:
    cmd: python src/train.py
    deps:
      - src/train.py
      - data/processed
    outs:
      - models/model.pkl
  evaluate:
    cmd: python src/evaluate.py
    deps:
      - src/evaluate.py
      - data/processed
      - models/model.pkl
    metrics:
      - metrics.txt:
          cache: false